### ISSUE TITLE
Typescript-Support cds-swagger-ui-express

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [chgeo/cds-swagger-ui-express#57]
Kindly guide me how to use cds-swagger-ui-express with Tyepscript
Thanks in advance

**Comment by Sandeep-Malhotra** [comment]
My aim is to use swagger-ui-express in typescript file (server.ts)
While trying to install types as dev dependencies I got an error ( npm i --save-dev @types/cds-swagger-ui-express)
<img width="695" alt="image" src="https://github.com/chgeo/cds-swagger-ui-express/assets/11954798/2938104f-f231-4085-8353-22aba4078fbd">

**Comment by chgeo** [comment]
There is no `@types/cds-swagger-ui-express`.  Just don't add it.
`cds-swagger-ui-express` provides some type hints using JSDoc.

**Comment by Sandeep-Malhotra** [comment]
Thanks I got below mentioned error while trying to use in server.ts file
<img width="898" alt="image" src="https://github.com/chgeo/cds-swagger-ui-express/assets/11954798/92f96a8b-feda-4817-b816-b9c7feeab300">

**Comment by chgeo** [comment]
Ok. As mentioned, this package has no TS support as of now.

This means you need to mitigate this fact when using the API.  There are typical patterns afaik (use `any` type, use `//ts-ignore` etc.). But I am no TS expert I am afraid.  There is lots of material out there that show you how to consume 'non TS-aware packages'.
