### ISSUE TITLE
Support OData flavors different than the default one of CAP

### ISSUE THREAD

**Issue by fidsusj** [chgeo/cds-swagger-ui-express#59]
Let's assume I have the following entities in my CAP project and expose them directly via an OData service:

```
using {managed} from '@sap/cds/common';

entity Authors {
  key name: String(64);
      age: Integer;
      [...]
      reviews: Association to many Reviews on reviews.reviewee = $self;
}

entity Reviews : managed {
  key uuid: UUID
      reviewee: Association to Authors;
      rating: Integer;
  [...]
}
```

I specify the desired OData flavor explicitly in my `.cdsrc.json` file like this:

```
{
  "odata": {
    "flavor": "x4"
  }
}
```

Now, if I do a `GET .../Reviews('43cf695f-4a13-4666-1240-d473f40fb23b')` I would receive a response object like this one: 
```
{
  "uuid": "43cf695f-4a13-4666-1240-d473f40fb23b",
  "reviewee": {
    "name": "John Doe"
  },
  "rating": 5
}
```

The [cds-swagger-ui-express](https://github.com/chgeo/cds-swagger-ui-express) library instead generates a swagger UI with a response object like this: 
```
{
  "uuid": "43cf695f-4a13-4666-1240-d473f40fb23b",
  "reviewee": "John Doe",
  "rating": 5
}
```

I guess the library cannot handle the custom OData flavor correctly in this case.

**Comment by chgeo** [comment]
`x4` has always been an SAP-internal OData flavor in a .  It now got removed w/ CAP 8.  Please see more in the internal release notes.
