### ISSUE TITLE
 TypeError: Cannot redefine property: _log with NodeJS 18

### ISSUE THREAD

**Issue by thakrawielitzki** [chgeo/cds-swagger-ui-express#61]
Hello,

I'm not 100% sure if cds-swagger-ui-express is responsible for this behaviour but, when we launch our CAP applications with NodeJS 18 we get this error:
>TypeError: Cannot redefine property: _log
>    at Function.defineProperties (<anonymous>)
>    at Object.<anonymous> (C:\Workspaces\asd\node_modules\@sap\cds-dk\lib\cds.js:4:25)
>    at Module._compile (node:internal/modules/cjs/loader:1254:14)
>    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)        
>    at Module.load (node:internal/modules/cjs/loader:1117:32)
>    at Module._load (node:internal/modules/cjs/loader:958:12)
>    at Module.require (node:internal/modules/cjs/loader:1141:19)
>    at require (node:internal/modules/cjs/helpers:110:18)
>    at Object.<anonymous> (C:\Workspaces\asd\node_modules\@sap\cds-dk\lib\index.js:1:30)
>    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Tested with NodeJS versions:
| NodeJS Version | result |
| - | - |
| 18.13.0 | TypeError: Cannot redefine property: _log |
| 18.15.0 | TypeError: Cannot redefine property: _log |
| 18.16.1 | TypeError: Cannot redefine property: _log |
| 16.16.0 | working - no error |

**Steps to reproduce**

1. Use NodeJS 18.16.1
1. init project

    ```
    cds init
    npm install --save-dev cds-swagger-ui-express
    ```

1. Add server.js

    ````js
    const cds = require ('@sap/cds')
    module.exports = cds.server
    
    if (process.env.NODE_ENV !== 'production') {
      const cds_swagger = require ('cds-swagger-ui-express')
      cds.on ('bootstrap', app => app.use (cds_swagger()) )
    }
    ```
1. start app with `cds run` or `cds watch` (cds watch gives a stacktrace)

Best Regards

**Comment by chgeo** [comment]
Thanks for the good bug report.
I have identified the issue and will provide a fix with the next patch of `@sap/cds-dk`.

**Comment by chgeo** [comment]
Also reported as https://answers.sap.com/questions/13912896/issue-with-3.html

**Comment by chgeo** [comment]
This is fixed in the meantime.
