### ISSUE TITLE
How to enable "Authorize" or pass Bearer token for xsuaa backed CDS services?

### ISSUE THREAD

**Issue by git-ashish** [chgeo/cds-swagger-ui-express#9]
Hello,

For secured CDS services, is there a way to enable Authorization as available in Swagger UI? For example to pass Auth Bearer token?

![image](https://user-images.githubusercontent.com/2697421/160787506-fd1af761-8adb-4692-9a94-f4bccb588fd7.png)

![image](https://user-images.githubusercontent.com/2697421/160787601-eafcf083-5605-4820-9e49-55cd32d87c9e.png)

How can the same be enabled for this package?

Many thanks!

**Comment by renandmc** [comment]
Same issue here, I tested with the swagger-ui-express package the same generated json but with the authentication configuration and it displays the button

**Comment by SirSimon04** [comment]
Are there any updates on this?

**Comment by chgeo** [comment]
The [documentation](https://cap.cloud.sap/docs/advanced/publishing-apis/openapi#authorization) on this is a bit vague, but here is an expample:

https://github.com/chgeo/cds-swagger-ui-express/blob/f3e988bada6019a09f0f66cc4bf3a081cf24d099/tests/app/services.cds#L23-L34

This leads to `securitySchemes` and `security` nodes added to the swagger spec.
Hope this helps.
