### ISSUE TITLE
Error: Cannot find module 'cds-swagger-ui-express'

### ISSUE THREAD

**Issue by zongqichen** [chgeo/cds-swagger-ui-express#91]
Deploy cds-swagger-ui-express to production, it still appears the error: Error: Cannot find module 'cds-swagger-ui-express'.
Environment:
-   "dependencies": {
    "@sap/cds": "^7",
    "@sap/cds-hana": "^2",
    "@sap/xssec": "^3",
    "express": "^4",
    "passport": "^0",
    "cds-swagger-ui-express": "^0.8.0"
  },
  "devDependencies": {
    "@cap-js/sqlite": "^1",
    "@sap/cds-dk": "^7",
    "cds-swagger-ui-express": "^0.8.0"
  }

**Comment by zongqichen** [comment]
The solution is removed cds-swagger-ui-express from devDependencies, as mentioned in https://github.com/chgeo/cds-swagger-ui-express/issues/8#issuecomment-1443918829

**Comment by chgeo** [comment]
Thanks for letting us know about the effect.  A module that is both a dependency and devDepencency can cause unpredictable behavior with npm I guess.
