### ISSUE TITLE
Open API Preview link missing for service annotated with `@protocol: rest`

### ISSUE THREAD

**Issue by gregorwolf** [chgeo/cds-swagger-ui-express#96]
Hi @chgeo,

I would think that #51 should have solved this issue, but I've added cds-swagger-ui-express 0.8.0 and see this result:

![Screenshot 2024-02-13 at 18 52 50](https://github.com/chgeo/cds-swagger-ui-express/assets/2639535/8692b85d-19ac-4f5e-8a4a-f2c6b0039224)

The OData V4 Service provides a link "Open API Preview" but the Service annotated with @protocol: 'rest' does not. Running:

```
cds compile srv --service all -o docs --to openapi
```

Works fine for the rest Service.

Best Regards
Gregor

**Comment by chgeo** [comment]
Thanks for catching this.  It got broken with sap/cds 7.6.2 where we wanted to suppress `$metadata` for non-OData services, but by mistake also removed all additional links.

Will be fixed with the next patch 7.6.4

**Comment by chgeo** [comment]
This should be now be fixed with sap/cds 7.6.4 and sap/cds-fiori 1.2.3

**Comment by gregorwolf** [comment]
Thank you @chgeo. I can confirm that it's working.
